sudo: required
addons:
  hosts:
  - boundless-test
services:
- docker
env:
  global:
  - PLUGIN_NAME=boundlesscommons
  matrix:
  - QGIS_VERSION_TAG=release PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master_2 PYTHON_EXECUTABLE=python PIP_EXECUTABLE=pip
  - QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
matrix:
  allow_failures:
  - env: QGIS_VERSION_TAG=master PYTHON_EXECUTABLE=python3 PIP_EXECUTABLE=pip3
before_install:
- docker pull boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG}
- docker tag boundlessgeo/qgis-testing-environment:${QGIS_VERSION_TAG} qgis-testing-environment
install:
- docker run -d --name qgis-testing-environment -v ${TRAVIS_BUILD_DIR}:/tests_directory -e DISPLAY=:99 qgis-testing-environment
- sleep 10
script:
- docker exec -it qgis-testing-environment sh -c "qgis_setup.sh $PLUGIN_NAME"
- docker exec -it qgis-testing-environment sh -c "echo 'No tests yet. Please add them
  here'"
notifications:
  slack:
    rooms:
      secure: hv5gS9/dEqtas5eIRTl9j6lFTfGpsh97AKyEggPjZq3WLaUPDtoGZH3OajrbRRz0xfSWisptRdhyMaYuqo4Hvd/FZo7YABn4TUiBbTrZPMlVuU6uUNa8yckpLNobkbU/oMn6Pdc4/UqJL4ky3WxNdTVdEPiA04YSwm6+kd6eJbAzkqwJJhfmngczsBW7QZV5TboFFaIRaWu3K3ABFDoYRA94MSnippOLqGAMzYdaUQee0Uj6QmEMsjAVAzWKmAFwmcoXAsFOj4iuEUK12uOM0H+sCkFkrviei8YOC7d9nH4p3Ugt8MrEN6aB0cspO2VJeoElDgI6biQaXdlmhxeTX2SnIXet7K7ejTMJCefL86wY9xs4RoKvN8X3U1/bRGAs8bkKd370pGrsL6EcaXeeD91uL+kKZSwaChJOuu4EISDj+yfsxdux9mFYEy6cvKd6sCAh8rau8FClruVd3saL3OtzGW5fNSgpfKxPwv8Rujd109xJ8XbFSliig2EPwolkHCg5crC6mRXFerG3i3G4ClOzBYEA3kJgadwFrAUXQF+vgQP8XHQDN3734WtjleCR2I8NRSnSejOsJ8TyhxW2DSR9D89BaZ8P7/VJuZiVyKXWE7xDK14IUkMoPilwcBCgPBD/w9VTzQNVa5RtjxxBuw9sS9fu18hXaibzTqc1z0s=
